# Generated by Django 4.0.4 on 2022-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=455)),
                ('artist', models.CharField(max_length=455)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
